website/website/apps/phone/urls.py
# -*- coding: utf-8 -*- 
from django.conf.urls import url

from .views import (AllCallView, CountView, DailyCallTimeView, DailyCountView, 
    DepartmentView, DonutView, EmployeeView, MyCallView)


urlpatterns = [
    url(r'^$', MyCallView.as_view(), name='my_calls'),
    url(r'^all-calls/$', AllCallView.as_view(), name='all_calls'),

    url(r'^api/count/$', CountView.as_view(), name='count'),
    url(r'^api/daily-count/$', DailyCountView.as_view(), name='daily_count'),
    url(r'^api/daily-call-time/$', DailyCallTimeView.as_view(), name='daily_call_time'),
    url(r'^api/department/$', DepartmentView.as_view(), name='department'),
    url(r'^api/donut/$', DonutView.as_view(), name='donut'),
    url(r'^api/employee/$', EmployeeView.as_view(), name='employee'),
    
]

website/website/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.contrib.staticfiles import views


urlpatterns = [ 
    url(r'^admin/', admin.site.urls),
    
    url(r'^login/', login, name='login', kwargs={'template_name': 'authentication/pages/_login.html'}),
    url(r'^logout/$', logout, name='logout', kwargs={'next_page': '/'}),

    url(r'^', include('website.apps.phone.urls', namespace='phone')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

website/website/apps/phone/models.py
# -*- coding: utf-8 -*-
from datetime import datetime, timedelta 
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.functional import lazy
from django.utils.translation import ugettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey
from uuslug import uuslug

from website.apps.authentication.models import CustomUser

from .choices import (CHART_TYPE_CHOICES, CHART_URL_CHOICES, 
    DIRECTION_CHOICES, INTERNAL_EXTERNAL_CHOICES, NUMBER_OF_CHART_CHOICES)


@python_2_unicode_compatible
class Department(models.Model):
    department_id = models.IntegerField(_('department id'), unique=True)
    name = models.CharField(_('name'), max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name',]
        verbose_name = _('Department')
        verbose_name_plural = _('Departments')

    def get_users(self):
        return self.users.all()


@python_2_unicode_compatible
class Call(models.Model):
    call_id = models.IntegerField(_('call id'), primary_key=True)
    user = models.ForeignKey(CustomUser)
    department = models.ForeignKey(Department)
    direction = models.CharField(_('direction'), max_length=1, choices=DIRECTION_CHOICES)
    internal_external = models.CharField(_('internal external'), max_length=1, choices=INTERNAL_EXTERNAL_CHOICES)
    start_time = models.DateTimeField(_('start time'))
    end_time = models.DateTimeField(_('end time'))
    talk_time_seconds = models.IntegerField(_('talk time seconds'))

    def __str__(self):
        return '%s: %s' % (self.user.get_full_name(), self.start_time.strftime('%d %b, %Y, %H:%M:%S'))

    class Meta:
        ordering = ['start_time', 'user',]
        verbose_name = _('Call')
        verbose_name_plural = _('Calls')


@python_2_unicode_compatible
class Page(models.Model):
    name = models.CharField(_('name'), max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Row(models.Model):
    name = models.CharField(_('name'), max_length=100, help_text=_('For admin reference purposes'))
    page = models.ForeignKey(Page, blank=True, null=True)
    number_of_charts = models.CharField(_('number of charts'), max_length=1, choices=NUMBER_OF_CHART_CHOICES)
    position = models.SmallIntegerField(default=0)

    def __str__(self):
        return '%s: %s' %  (self.page, self.name)

    class Meta:
        ordering = ['page', 'position',]

    def get_bootstrap_col_classes(self):
        if self.number_of_charts == '1':
            return 'col-sm-12'
        elif self.number_of_charts == '2':
            return 'col-sm-12 col-lg-6'
        elif self.number_of_charts == '4':
            return 'col-xs-12 col-sm-6 col-lg-3'
        return ''


@python_2_unicode_compatible
class Chart(models.Model):
    name = models.CharField(_('name'), max_length=100, help_text=_('For admin reference purposes'))
    title = models.CharField(_('title'), max_length=100) 
    url = models.CharField(_('url'), max_length=100, choices=CHART_URL_CHOICES)
    query_string = models.CharField(_('query string'), max_length=200, blank=True, null=True)
    chart_type = models.CharField(_('chart type'), max_length=50, choices=CHART_TYPE_CHOICES)
    rows = models.ManyToManyField(Row, through='RowChart', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Chart')
        verbose_name_plural = _('Charts')

    def get_url(self):
        return reverse('phone:%s' % self.url)


@python_2_unicode_compatible
class RowChart(models.Model):
    row = models.ForeignKey(Row)
    chart = models.ForeignKey(Chart)
    position = models.SmallIntegerField(default=0)

    class Meta:
        ordering = ['position',]

website/website/apps/phone/forms.py
# -*- coding: utf-8 -*- 
from django.conf import settings
from django import forms
from website.apps.authentication.models import CustomUser

from .fields import DateRangeField
from .models import Department


class FilterBarForm(forms.Form):
    date_range = DateRangeField(required=False, input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.TextInput(attrs={
            'placeholder': 'Date range', 
            'class': 'form-control datepicker'
        }))


class FullFilterBarForm(FilterBarForm):
    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')

        super().__init__(*args, **kwargs)
        
        if request.user.is_superuser:
            # superusers can see all
            departments = Department.objects.all()
            users = CustomUser.objects.all()
        else:
            # else only show the departments they're authorised to see
            departments = request.user.departments_can_view.all()
            department_pks = departments.values_list('pk', flat=True)
            users = CustomUser.objects.filter(department__pk__in=department_pks)

        myfilters = [('u%s' % u.pk, u.get_full_name()) for u in users]
        myfilters += [('d%s'% d.pk, d.name) for d in departments]
        myfilters = sorted(myfilters, key=lambda x: x[1])

        self.fields['filters'] = forms.MultipleChoiceField(required=False, choices=myfilters)

website/website/apps/phone/views.py
# -*- coding: utf-8 -*- 
from datetime import datetime, timedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg, Count, Q, Sum, Value as V
from django.db.models.functions import Concat, TruncDay
from django.http import HttpResponse
from django.views.generic import TemplateView
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

import json

from .choices import DIRECTION_CHOICES, INTERNAL_EXTERNAL_CHOICES
from .forms import FilterBarForm, FullFilterBarForm
from .models import Call, Chart, Page
from .utils import datetimeRange


class MyCallView(LoginRequiredMixin, TemplateView):
    template_name = 'phone/pages/_my_calls.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = FilterBarForm()
        context['only_me'] = True
        context['page'] = Page.objects.filter(name__icontains='my calls').first()
        return context


class AllCallView(LoginRequiredMixin, TemplateView):
    template_name = 'phone/pages/_all_calls.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = FullFilterBarForm(request=self.request)
        context['only_me'] = False
        context['page'] = Page.objects.filter(name__icontains='all calls').first()
        return context


class BaseAPIView(LoginRequiredMixin, APIView):
    date_format = '%d %b'
    direction = None
    internal_external = None
    form = None
    only_me = False

    def dispatch(self, request, *args, **kwargs):
        self.form = self._get_form()
        self._set_extra_query_params()
        return super().dispatch(request, *args, **kwargs)

    def _get_form(self):
        only_me = self.request.GET.get('only_me', False)
        if only_me == 'True':
            self.only_me = True
            return FilterBarForm(self.request.GET)

        return FullFilterBarForm(self.request.GET, request=self.request)

    def _set_extra_query_params(self):
        internal_external = self.request.GET.get('internal_external', None)
        direction = self.request.GET.get('direction', None)

        valid_list = [None,'0','1']

        if internal_external not in valid_list or direction not in valid_list:
            self._return_error('form is not valid')
        
        self.internal_external = internal_external
        self.direction = direction

    def _return_error(self, msg):
        return Response({
            'error': msg
        }, status=status.HTTP_400_BAD_REQUEST)

    def _get_colour(self, direction, internal_external):
        if direction is None and internal_external is None:
            return '003b4b'
        elif int(direction) == 0 and int(internal_external) == 0:
            return '#b01658'
        elif int(direction) == 0 and int(internal_external) == 1:
            return '#009b87'
        elif int(direction) == 1 and int(internal_external) == 0:
            return '#ecaa00'
        else:
            return '#003b4b'

    def _get_names(self, direction, internal_external):
        name = ''

        for choice in DIRECTION_CHOICES:
            if choice[0] == int(direction):
                name += choice[1]
                break

        for choice in INTERNAL_EXTERNAL_CHOICES:
            if choice[0] == int(internal_external):
                name += '/%s' % choice[1]
                break

        return name

    def _get_calls(self):
        date_from, date_to = self.form.cleaned_data['date_range']

        q_objects = Q()

        if date_from:
            q_objects &= Q(start_time__gte=date_from)

        if date_to:
            q_objects &= Q(start_time__lt=date_to + timedelta(days=1))

        if self.internal_external:
            q_objects &= Q(internal_external=self.internal_external)

        if self.direction:
            q_objects &= Q(direction=self.direction)

        if self.only_me:
            q_objects &= Q(user=self.request.user)

        if type(self.form) == FullFilterBarForm:
            q_user_filter_objects = Q()
            q_department_filter_objects = Q()

            for flter in self.form.cleaned_data['filters']:
                if flter[0] == 'u':
                    q_user_filter_objects |= Q(user__pk=flter[1:])
                elif flter[0] == 'd':
                    q_department_filter_objects |= Q(department__pk=flter[1:])

            q_objects &= q_user_filter_objects
            q_objects &= q_department_filter_objects
        
        return Call.objects.filter(q_objects).annotate(
                date=TruncDay('start_time')
            ).order_by('date')

    def _get_daily_call_counts(self):
        calls = self._get_calls()
        return calls.values(
                'date', 'direction', 'internal_external'
            ).annotate(
                value=Count('pk')
            ).order_by('date', 'direction', 'internal_external')

    def _get_daily_call_time(self):
        calls = self._get_calls()
        return calls.values(
                'date', 'direction', 'internal_external'
            ).annotate(
                value=Avg('talk_time_seconds')
            ).order_by('date', 'direction', 'internal_external')        

    def _get_daily_series(self, queryset, query_type=None):
        # categories are each date
        categories = []

        # define two by two matrix for internal/external/inbound/outbound
        # these are defined nicely by the 0/1 values which means can index
        # matrix appropriately.
        data_lists = [[[],[]] for x in range(2)]
        data_results = [[{},{}] for x in range(2)]

        dict_date_format = '%d %b %y'

        # loop through data to get into format for date loop
        # todo: surely there's a more efficient way to
        # to this and avoid the unnecessary double loop.
        for call in queryset:
            call_date = datetime.strftime(call['date'], dict_date_format)
            direction = int(call['direction'])
            internal_external = int(call['internal_external'])

            # if its an average call change to the minutes and round appropriately
            value = call['value']
            if query_type == 'seconds':
                value = round(value / 60, 1)

            data_results[direction][internal_external][call_date] = value

        # loop through each date between the date form to date
        # to, so dates with no records will still show as zero
        date_from, date_to = self.form.cleaned_data['date_range']
        if date_from and date_to:
            for day in datetimeRange(date_from, date_to):
                day_str = datetime.strftime(day, dict_date_format)
                categories.append(day_str)

                # loop through each of the data types
                for i in range(2):
                    for j in range(2):
                        data_lists[i][j].append(data_results[i][j].get(day_str, 0))

        # loop through each of the data types in the matrix 
        # and append to the series
        series = []
        for i in range(2):
            for j in range(2):
                series.append({
                    'name': self._get_names(i,j),
                    'data': data_lists[i][j],
                    'color': self._get_colour(i,j),
                })

        return categories, series


class DailyCountView(BaseAPIView):
    def get(self, request, format=None):
        if not self.form.is_valid():
            return self._return_error('form is not valid')

        calls = self._get_daily_call_counts()
        categories, series = self._get_daily_series(calls)

        return Response({
            'categories': categories,
            'series': series,
        })


class DailyCallTimeView(BaseAPIView):
    def get(self, request, format=None):
        if not self.form.is_valid():
            return self._return_error('form is not valid')

        calls = self._get_daily_call_time()
        categories, series = self._get_daily_series(queryset=calls, query_type='seconds')

        return Response({
            'categories': categories,
            'series': series,
        })


class DonutView(BaseAPIView):
    def get(self, request, format=None):
        if not self.form.is_valid():
            return self._return_error('form is not valid')
        
        calls = self._get_calls()
        calls = calls.values('internal_external', 'direction').annotate(
            count=Count('pk')).order_by('internal_external', 'direction')

        results = []

        for result in calls:
            results.append({
                'name': self._get_names(result['direction'], result['internal_external']),
                'y': result['count'],
                'color': self._get_colour(result['direction'], result['internal_external']),
            })

        return Response(results)


class CountView(BaseAPIView):
    def get(self, request, format=None):
        if not self.form.is_valid():
            return self._return_error('form is not valid')

        queryset = self._get_calls()

        return Response({
            'count': queryset.count(),
            'colour': self._get_colour(self.direction, self.internal_external),
        })


class DepartmentView(BaseAPIView):
    def get(self, request, format=None):
        if not self.form.is_valid():
            return self._return_error('form is not valid')
        
        queryset = self._get_calls()
        queryset = queryset.values(
                'department__name',
                'internal_external', 
                'direction'
            ).annotate(
                count=Count('pk'),
            ).order_by('department__name')

        categories = queryset.values_list('department__name', flat=True).distinct()
        series = []

        for i in range(2):
            for j in range(2):
                series.append({

website/website/apps/phone/templates/phone/pages/_all_calls.html
{% extends 'phone/pages/_base.html' %}
{% load widget_tweaks %}

{% block title %}Welcome {{ request.user.first_name }} to your phone reporting dashboard{% endblock %}

{% block content %}
    <div id="page-content-wrapper">
        <section class="header-bar">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-10">
                        <a href="#menu-toggle" class="btn btn-blue toggle-menu" id="menu-toggle"><i class="fa fa-bars"></i>  </a>
                        <h1 class="welcome-msg">Welcome {{ request.user.first_name }}</h1>
                    </div>
                    <div class="col-xs-2">
                        <a class="btn btn-blue logout" href="{% url 'logout' %}"><i class="fa fa-sign-out"></i>Logout</a>
                    </div>
                </div>
            </div>
        </section>

        <section class="filter-bar">
            <form id="filter-bar-form">
                <div class="row">
                    <div class="col-xs-12 col-md-4">
                        {% include 'phone/reusable/_datepicker.html' %}
                    </div>
                    <div class="col-xs-12 col-md-8">
                        {% if form.filters.field.choices|length > 0 %}
                            {{ form.filters|add_class:"multipleSelect" }}
                        {% endif %}
                    </div>
                </div>
            </form>
        </section>

        {% include 'phone/reusable/_charts.html' %}

    </div>

{% endblock %}

website/website/apps/phone/templates/phone/pages/_base.html
{% extends 'base.html' %}
{% load sekizai_tags staticfiles thumbnail %}

{% block pagecontent %}
    <div id="sidebar-wrapper">
        <aside class="sidebar">
            <section class="branding">
                {% thumbnail request.user.image "100x100" crop="center" as im %}
                    <img class="circle" src="{{ im.url }}">
                {% endthumbnail %}
                <h3>{{ request.user.get_full_name }}</h3>
                <span class="title">{{ request.user.company_position }}</span>     
            </section>
            <section>
                <nav class="sidebar-nav">
                    <ul>
                        {% url 'phone:my_calls' as url %}
                        <li {% if request.get_full_path == url %}class="active"{% endif %}><a href="{{ url }}"><i class="fa fa-user"></i><span>My Calls</span></a></li>
                        {% url 'phone:all_calls' as url %}
                        <li {% if request.get_full_path == url %}class="active"{% endif %}><a href="{{ url }}"><i class="fa fa-users"></i><span>All Calls</span></a></li>                        
                    </ul>
                </nav>
            </section>
        </aside>
    </div>

    {% block content %}{% endblock %}

    <a href="javascript:" id="return-to-top" class="btn-blue"><i class="fa fa-chevron-up"></i></a>

    {% addtoblock "css" %}
        <link rel="stylesheet" type="text/css" href="{% static 'phone/css/fastselect.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'phone/css/styles.css' %}">
    {% endaddtoblock %}

    {% addtoblock "js" %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.9/highcharts.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.9/highcharts-more.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.9/modules/exporting.js"></script>

        <script src="{% static 'phone/js/fastselect.standalone.min.js' %}"></script>

        <script src="{% static 'phone/js/custom.js' %}"></script>
    {% endaddtoblock %}

{% endblock %}

website/website/apps/phone/templates/phone/pages/_my_calls.html
{% extends 'phone/pages/_base.html' %}
{% load sekizai_tags widget_tweaks staticfiles %}

{% block title %}Welcome {{ request.user.first_name }} to your phone reporting dashboard{% endblock %}

{% block content %}
    <div id="page-content-wrapper">
        <section class="header-bar">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-10">
                        <a href="#menu-toggle" class="btn btn-blue toggle-menu" id="menu-toggle"><i class="fa fa-bars"></i>  </a>
                        <h1 class="welcome-msg">Welcome {{ request.user.first_name }}</h1>
                    </div>
                    <div class="col-xs-2">
                        <a class="btn btn-blue logout" href="{% url 'logout' %}"><i class="fa fa-sign-out"></i>Logout</a>
                    </div>
                </div>
            </div>
        </section>

        <section class="filter-bar">
            <form id="filter-bar-form">
                <div class="row">
                    <div class="col-xs-12 col-md-4">
                        {% include 'phone/reusable/_datepicker.html' %}
                    </div>
                </div>
            </form>
        </section>

        <section class="chart-section">
            <div class="container-fluid">
                <div class="row">
                    {% for chart in charts %}
                        <div class="col-xs-12 col-md-6">
                            <div id="chart-{{ chart.pk }}" class="chart"></div>
                        </div>
                        {% if forloop.counter|divisibleby:"2" and not forloop.last %}
                            </div><div class="row">
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </section>

    </div>

    

    {% addtoblock "js" %}
        <script src="{% static 'phone/js/mycharts.js' %}"></script>
        <script type="text/javascript">
            function setCharts(){
                var form = $('#filter-bar-form');
                var qs = '?' + form.serialize();

                {% for chart in charts %}
                    $('#chart-{{ chart.pk}}').mycharts('{{ chart.chart_type }}', {
                        title: '{{ chart.title }}',
                        url: '{{ chart.get_url }}' + qs + '{{ chart.query_string|default_if_none:"" }}'
                    });
                {% endfor %}                
            }

            $(function(){
                $('#filter-bar-form').change(function () {
                    // the datepicker is changing the form 
                    // on load, so no need to call initially
                    setCharts();
                });

            })

        </script>
    {% endaddtoblock %} 

{% endblock %}